### ISSUE TITLE
[tracking] Add sign up page

### ISSUE THREAD

**Issue by Wrench56** [MiddleSchoolMathGuide/frontend#17]
- [x] Add sign up page
- [x] Add gmail verification
- [x] Embed Sign Up button in login page
- [x] Use `/user/create` API endpoint
- [x] Redirect to login page

**Comment by Scharpp** [comment]
What do you need for gmail verification? Is verifying that the email is a gmail enough for now?

**Comment by Wrench56** [comment]
@Scharpp Yes.
