### ISSUE TITLE
[tracking] Login page

### ISSUE THREAD

**Issue by Wrench56** [MiddleSchoolMathGuide/frontend#2]
- [x] Create a login page
- [x] Create authentication through the API
- [x] Create "blocked" page
