### ISSUE TITLE
[tracking] Lesson design

### ISSUE THREAD

**Issue by Wrench56** [MiddleSchoolMathGuide/frontend#39]
- [x] Load data from `/api/t/{topic}/{unit}/{lesson}`
- [x] Parse table of content data
- [x] Parse `LessonBar` data
- [x] Parse credits data
- [x] Add static credits data
- [x] Add loading spinner

**Comment by Wrench56** [comment]
The API endpoints `/api/topics` and `/api/unit_context/{topic}/{unit}` have been added. The first one returns the `title` and `description` fields of all the topics in the database. The latter one returns all `units` in of a certain `topic` and all `lessons` of a certain `unit`. This is likely to change in the future and be split into `/api/{topic}/units` and `/api/{topic}/{unit}/lessons`.

**Comment by Wrench56** [comment]
API issues resolved in #46.

**Comment by Wrench56** [comment]
🥳
