### ISSUE TITLE
[tracking] Create /me page

### ISSUE THREAD

**Issue by Wrench56** [MiddleSchoolMathGuide/frontend#6]
- [x] Create basic HTML
- [x] Show `profile` fields
- [x] Put it behind login
- [x] Add admin/moderator/user version
